#+TITLE: Module 1 Questions
#+SETUPFILE: ../../template-2.org
Created on 2020-07-17/15:54
* Module 1 Questions
** Expressions
+ *Question 1*
file:../../screenshots/M1S1Q1.png

#+BEGIN_SRC racket
(sqrt (+ (sqr 3) (sqr 4)))

#+END_SRC

#+RESULTS:
: 5

: RESULTS:
: 5

 + /this is pretty much the most difficult math seen in this course/


+ *Question 2*
  + If you see #i2.718281828459045 appear in the interaction pane, it means:
    1. It's an imaginary number.
    2. Someone just sent a strange tweet.
    3. /It's a number very close to 2.718281828459045./
    4. I thought you said there wouldn't be much math!

+ *Question 3*
  + Which of the following are expressions:
    1. src_racket{sqr}

    2. src_racket{(+ 2 3)}  <-

    3. src_racket{+}

    4. src_racket{(sqrt 2)}i  <-

    5. src_racket{#i1.4142135623730951}  <-

    6. src_racket{1}  <-

    7. src_racket{)}

  + /At this point in the course an expression is either a value, or of the form src_racket{(<primitive> <expression> ...)}. We will shortly add to our vocabulary of expressions./

+ *Question 4*
* Intro lab questions
** Problem 1
+ Use string primitives to create an expression that concatenates =prefix= and =suffix= and adds "_" between them (so you get "hello_world" when you run the program).

** Problem 2
+ Use string primitives to create an expression that adds "_" at position i (the position that is i characters from the left of the string).  Again, in this particular example, the expected result is "hello_world".

** Problem 3
+ Create an expression that counts the number of pixels in the CAT image.

** Problem 4
+ Create an expression that computes whether CAT is "tall" (height is larger than its width), "wide" (width is larger than its height), or "square" (height is the same as its width).

** Problem 5
+ Create an expression that computes whether the first character in STR is "h". In this example, the expected result is true.
