#+TITLE: Lecture 1
#+SETUPFILE: ../template-1.org
- tags :MIT: :shell:

*  The Shell
** Usage
+ The command =date= will print the current date.
    : RESULTS:
    : Mon 13 Jul 2020 01:16:10 PDT
+ Shell commands can also be executed with /arguments./
  #+BEGIN_SRC shell
echo hello
  #+END_SRC
  : RESULTS:
  : hello

  In this case, ~echo~ was the command, and ~hello~ was the argument.
  The echo command will print out its arguments.
  + In order to parse arguments which are multiple words long, use ~'~ or ~"~ .
    You could also use ~\~ to escape relevant characters.


+ ~which~ can be used to find the location of which program is being executed.
  #+BEGIN_SRC shell
which python
  #+END_SRC
  : RESULTS:
  : /usr/bin/python

** Connecting Programs
+ Programs contain two streams, an input and an output. Programs will read from the input stream and print into the output stream.

  This way, it is possible to change the the input or output away from the terminal and reroute those streams.

  + ~< file~ and ~> file~ can both be easily used to redirect the input and output streams.

    #+BEGIN_SRC shell
echo hello > hello.txt
cat < hello.txt > hello2.txt
    #+END_SRC
    This print the argument of ~echo~, which is ~hello~, into =hello.txt=. Then, it will print the contents of =hello.txt= using the ~cat~ command, and pipe it into =hello2.txt=.

  + Furthermore, the use of ~|~ will allow you to "chain" commands together so that the output of one is the input of another.
    #+BEGIN_SRC shell
cat coolfile.txt | grep 'cool text'
    #+END_SRC
    This will print the contents of =coolfile.txt= and then ~grep~ for the string =cool text=.
