#+TITLE: Lecture 2
#+SETUPFILE: ../template-1.org
Created on 2020-07-13/02:21

* Scripting
** Defining variables
+ To define a variable, you can use ~foo=bar~.
  #+BEGIN_SRC shell
foo=bar
echo $foo
  #+END_SRC

  #+RESULTS:
  : bar

  : RESULTS:
  : bar

+ ~foo = bar~ would not work as it is the equivalent as ~foo~ calling upon the ===, and =bar= arguments.

  + Strings can be desginated using ~'~ and ~"~.
    + ~'~ is used for literal strings and will not subsitute variables.
    + ~"~ will be able to subsitute variables.
      
  #+BEGIN_SRC shell
    foo=bar
    echo "$foo"
    echo '$foo'
  #+END_SRC

  #+RESULTS:
  | bar  |
  | $foo |

       : RESULTS:
        | bar  |
        | $foo |
** Functions
+ Bash supports control flow techniques such as ~if~, ~case~, and ~for~.
+ Bash also has functions which take arguments and operate them.

  #+BEGIN_SRC shell
mcd () {
    mkdir -p "$1"
cd "$1"
}
  #+END_SRC

  #+RESULTS:

+ In this scenario, ~$1~ is the first argument to the function.
    + This function will make a directory with the name of the argument ~$1~ and ~cd~ into that folder.

      
+ In bash, there are a number of relevant variables.
  | $0       | Name of script                                            |
  | $1 to $9 | Arguments to the script                                   |
  | $@       | All the arguments                                         |
  | $#       | Number of arguments                                       |
  | $?       | Return code of the previous command                       |
  | $$       | Process identification number (PID) of the current script |
  | !!       | Entire last command, including arguments.                 |
  | $_       | Last argument from previous command.                      |

+ A full list can be found [[https://www.tldp.org/LDP/abs/html/special-chars.html][here.]]

** Error Codes and Outputs
+ A return code of =0= means that the previous function ran *without* any issues.
+ Return code of =1= means there *was* an issue.

  
+ /True/ will return error code =0=.
+ /False/ will return error code =1=.


+ This way, error codes can be used conditionally to execute commands.


  + =||= is equivalent to =or=. If error code returns one, it will run the second command.
    + The second command will not run if the first command did not return an error code.
      #+BEGIN_SRC shell
    false || echo "Oops fail"
    true || echo "This prints nothing"
      #+END_SRC
      : RESULTS:
      : Oops fail

  + Similarly ~&&~ symbolizes =and=. If the first command runs successfully, the second will too.
    + If the first command returns an error code, the second will not run.
    #+BEGIN_SRC shell
true && echo "Prints"
    #+END_SRC

    : RESULTS:
    : Prints

    #+BEGIN_SRC shell
false && echo "Doesn't print"
    #+END_SRC

    : RESULTS:
+ The usage of ~;~ will always run the next command.

+ The output of a command can be stored within a variable using:
  #+BEGIN_SRC shell
foo=$(pwd)
echo "We are in $(pwd)"
echo "We are in $foo"
  #+END_SRC

  : RESULTS:
  | We | are | in | /Users/johnmao/johnrmao.github.io/org/MissingMIT |
  | We | are | in | /Users/johnmao/johnrmao.github.io/org/MissingMIT |

** Substitutions

+ To feed the output of a command as a variable, use /command subsitution./

  + ~$( CMD )~ will execute =CMD= and substitute ~$( CMD )~ with the output.

+ There is similar feature known as /process subsitution./

  + ~<( CMD )~ will execute =CMD= and place the output within a temporary file, replacing ~<()~ with that file's name.

+ An example of what's mentioned above would be:
  #+BEGIN_SRC shell
echo "Starting program at $(date)" # The current date will replace $(date) in this scenario
echo "Running program $0 with $# arguments with pid $$"

for file in "$@"; do # -ne is comparing to see if $@ does not equal 0
    grep foobar "$file" > /dev/null 2> /dev/null
    # if nothing is found, grep returns exit status 1
    # redirected STDOUT and STDERR to null register as they are irrelevant
    if [[ $? -ne 0 ]]; then # $? is referring to the return code of grep here
        echo "File $file does not have any foobar, adding one"
        echo "# foobar" >> "$file"
    fi
done
  #+END_SRC
+ Here, using ~-ne~ we can test whether ~$?~ was not equal to 0.
+ The script above will take arguments and ~grep~ them for "foobar" and will add a "foobar" if it was not detected.

  
+ It is generally safer to use ~[[ ]]~ instead of single brackets in bash.

** Globbing

+ Globbing refers to techniques which makes expanding expressions or filenames easier.
  

  + =?= and =*= can be used to match one or any characters respectively.

    + With files =foo, foo1, foo2, foo3, foo12, bar=, using ~rm foo?~ will delete =foo1, foo2,= and =foo3=. Running ~rm foo*~ will remove all but =bar=.


+ Curly braces ={}= can also be used to expand common substrings in a series of commands.
  #+BEGIN_SRC shell
convert image.png image.jpg
# equivalent to
convert image.{png,jpg}
  #+END_SRC

+ Similarly, it can also be used for this:
  #+BEGIN_SRC shell
mv *.{.sh,.py} new_folder
  #+END_SRC
+ All .sh and .py files will be moved to a new folder.

** SHEBANG!

+ It is important to include a *shebang* line at the top of scripts to tell the kernel which interpreter to use.
  #+BEGIN_SRC python
#!/usr/local/bin/python
import sys
for arg in reversed(sys.argv[1:]):
    print(arg)
  #+END_SRC
+ Here, the shebang line tells the kernel to use a python interpreter.


+ It is important to differentiate between functions and scripts.
  + Scripts can be written in *any* language, but functions need to be written in the *same* language as the shell.

    
* Tools
+ Check the man pages.

  
  ~man CMD~
+ Or, check the tldr.


  ~tldr CMD~
* Search
** Finding files
+ The ~find~ command can be used to recursively find files.
  #+BEGIN_SRC shell
# Find all directories named src
find . -name src -type d
# Find all python files that have a folder named test in their path
find . -path '*/test/*.py' -type f
# Find all files modified in the last day
find . -mtime -1
# Find all zip files with size in range 500k to 10M
find . -size +500k -size -10M -name '*.tar.gz'
  #+END_SRC


+ Actions can also be performed over files which match the search quary.
  #+BEGIN_SRC shell
# Delete all files with .tmp extension
find . -name '*.tmp' -exec rm {} \;
# Find all PNG files and covert them to jpg
find . -name '*.png' convert {} {}.jpg \;
  #+END_SRC


+ The use of =-iname= will make searches case insensitive.


** Finding code
+ =grep= can be used to find patterns from input text.
  + Some useful flags:
    | -C | Context around the matching line                    |
    | -v | Inverting a match, printing all that does not match |
    | -R | Recursively search directories for files matching string  |


+ Other useful alternatives for =grep= include =ack=, =ag=, and =rg=.


** Finding shell commands
+



* Navigation
